name: pmagpy-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.14.0
  - matplotlib=2.2.2
  - pandas=0.23.1
  - basemap=1.1.0
  - basemap-data-hires=1.1.0
  - scipy=1.0.0
  - pip:
    - pmagpy
    - pmagpy-cli
